// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iigvmcmtzxbtrtgqtupz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlpZ3ZtY210enhidHJ0Z3F0dXB6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5MjE1NjcsImV4cCI6MjA3MDQ5NzU2N30.AX17D5_t5UBSwebpPBaqhtB3eotQgnBaUW2-n4G-DTY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
